--------------------------------------------------------
--  File created - среда-январь-25-2017   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table UNIVERSITY
--------------------------------------------------------

  CREATE TABLE "TEST"."UNIVERSITY" 
   (	"UNIVERSITY_NAME" VARCHAR2(30 BYTE), 
	"QUANT_ACCEPT" NUMBER(*,0), 
	"SPEC_NAME" VARCHAR2(30 BYTE), 
	"CLOSED" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into TEST.UNIVERSITY
SET DEFINE OFF;
Insert into TEST.UNIVERSITY (UNIVERSITY_NAME,QUANT_ACCEPT,SPEC_NAME,CLOSED) values ('KPI','1','sd5ds4v5','0');
Insert into TEST.UNIVERSITY (UNIVERSITY_NAME,QUANT_ACCEPT,SPEC_NAME,CLOSED) values ('KPI','1','fdvnkdf','0');
Insert into TEST.UNIVERSITY (UNIVERSITY_NAME,QUANT_ACCEPT,SPEC_NAME,CLOSED) values ('KPI','1','Filologia','1');
Insert into TEST.UNIVERSITY (UNIVERSITY_NAME,QUANT_ACCEPT,SPEC_NAME,CLOSED) values ('National SH','1','sdhjfhjs','0');
Insert into TEST.UNIVERSITY (UNIVERSITY_NAME,QUANT_ACCEPT,SPEC_NAME,CLOSED) values ('National SH','1','hhhh','0');
Insert into TEST.UNIVERSITY (UNIVERSITY_NAME,QUANT_ACCEPT,SPEC_NAME,CLOSED) values ('KPI','1','sdjkf545','0');
Insert into TEST.UNIVERSITY (UNIVERSITY_NAME,QUANT_ACCEPT,SPEC_NAME,CLOSED) values ('KPI','1','adsa22','0');
Insert into TEST.UNIVERSITY (UNIVERSITY_NAME,QUANT_ACCEPT,SPEC_NAME,CLOSED) values ('KPI','1','fghjkl','0');
Insert into TEST.UNIVERSITY (UNIVERSITY_NAME,QUANT_ACCEPT,SPEC_NAME,CLOSED) values ('NAU','1','tfghjk','0');
Insert into TEST.UNIVERSITY (UNIVERSITY_NAME,QUANT_ACCEPT,SPEC_NAME,CLOSED) values ('KPI','1','AppMath','0');
Insert into TEST.UNIVERSITY (UNIVERSITY_NAME,QUANT_ACCEPT,SPEC_NAME,CLOSED) values ('NUHTA','33','pivovarenie','1');
--------------------------------------------------------
--  DDL for Index UNIVERSITY_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TEST"."UNIVERSITY_PK" ON "TEST"."UNIVERSITY" ("UNIVERSITY_NAME", "SPEC_NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table UNIVERSITY
--------------------------------------------------------

  ALTER TABLE "TEST"."UNIVERSITY" MODIFY ("UNIVERSITY_NAME" NOT NULL ENABLE);
 
  ALTER TABLE "TEST"."UNIVERSITY" MODIFY ("SPEC_NAME" NOT NULL ENABLE);
 
  ALTER TABLE "TEST"."UNIVERSITY" ADD CONSTRAINT "UNIVERSITY_PK" PRIMARY KEY ("UNIVERSITY_NAME", "SPEC_NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table UNIVERSITY
--------------------------------------------------------

  ALTER TABLE "TEST"."UNIVERSITY" ADD CONSTRAINT "UNIVERSITY_UNIVERSITIES_FK1" FOREIGN KEY ("UNIVERSITY_NAME")
	  REFERENCES "TEST"."UNIVERSITIES" ("UNIVERSITY_NAME") ON DELETE CASCADE ENABLE;
