--------------------------------------------------------
--  File created - среда-январь-25-2017   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table UNIVERSITIES
--------------------------------------------------------

  CREATE TABLE "TEST"."UNIVERSITIES" 
   (	"UNIVERSITY_NAME" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into TEST.UNIVERSITIES
SET DEFINE OFF;
Insert into TEST.UNIVERSITIES (UNIVERSITY_NAME) values ('KPI');
Insert into TEST.UNIVERSITIES (UNIVERSITY_NAME) values ('NAU');
Insert into TEST.UNIVERSITIES (UNIVERSITY_NAME) values ('NUHTA');
Insert into TEST.UNIVERSITIES (UNIVERSITY_NAME) values ('National SH');
--------------------------------------------------------
--  DDL for Index UNIVERSITIES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TEST"."UNIVERSITIES_PK" ON "TEST"."UNIVERSITIES" ("UNIVERSITY_NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table UNIVERSITIES
--------------------------------------------------------

  ALTER TABLE "TEST"."UNIVERSITIES" MODIFY ("UNIVERSITY_NAME" NOT NULL ENABLE);
 
  ALTER TABLE "TEST"."UNIVERSITIES" ADD CONSTRAINT "UNIVERSITIES_PK" PRIMARY KEY ("UNIVERSITY_NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
